INHERIT: mkdocs_dev.yml

plugins:
    # Only use minify when building for prod, as it takes a relatively
    # long time to run.
    minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true

    # Don't need redirects in dev
    redirects:
      redirect_maps:
          3/channel-modes.md: 4/channel-modes.md
          3/commands/index.md: 4/commands/index.md
          3/configuration-changes.md: 3/breaking-changes.md
          3/configuration/index.md: 4/configuration/index.md
          3/configuration/useful-snippets.md: 4/configuration/useful-snippets.md
          3/extended-bans.md: 4/extended-bans.md
          3/index.md: index.md
          3/installation/centos.md: 4/installation/rhel.md
          3/installation/debian.md: 4/installation/debian.md
          3/installation/index.md: 4/installation/index.md
          3/installation/rocky.md: 4/installation/rhel.md
          3/installation/source.md: 4/installation/source.md
          3/installation/ubuntu.md: 4/installation/ubuntu.md
          3/installation/windows-source.md: 4/installation/windows-source.md
          3/installation/windows.md: 4/installation/windows.md
          3/modules/abbreviation.md: 4/modules/abbreviation.yml
          3/modules/alias.md: 4/modules/alias.yml
          3/modules/allowinvite.md: 4/modules/allowinvite.yml
          3/modules/alltime.md: 4/modules/alltime.yml
          3/modules/anticaps.md: 4/modules/anticaps.yml
          3/modules/argon2.md: 4/modules/argon2.yml
          3/modules/auditorium.md: 4/modules/auditorium.yml
          3/modules/autoop.md: 4/modules/autoop.yml
          3/modules/banexception.md: 4/modules/banexception.yml
          3/modules/banredirect.md: 4/modules/banredirect.yml
          3/modules/bcrypt.md: 4/modules/bcrypt.yml
          3/modules/blockamsg.md: 4/modules/blockamsg.yml
          3/modules/blockcaps.md: 4/modules/anticaps.yml
          3/modules/blockcolor.md: 4/modules/blockcolor.yml
          3/modules/botmode.md: 4/modules/botmode.yml
          3/modules/callerid.md: 4/modules/callerid.yml
          3/modules/cap.md: 4/modules/cap.yml
          3/modules/cban.md: 4/modules/cban.yml
          3/modules/censor.md: 4/moved-modules.md
          3/modules/cgiirc.md: 4/modules/gateway.yml
          3/modules/chancreate.md: 4/modules/chancreate.yml
          3/modules/chanfilter.md: 4/modules/chanfilter.yml
          3/modules/chanhistory.md: 4/modules/chanhistory.yml
          3/modules/chanlog.md: 4/modules/chanlog.yml
          3/modules/channames.md: 4/modules/channames.yml
          3/modules/channelban.md: 4/modules/channelban.yml
          3/modules/check.md: 4/modules/check.yml
          3/modules/chghost.md: 4/modules/chghost.yml
          3/modules/chgident.md: 4/modules/chgident.yml
          3/modules/chgname.md: 4/modules/chgname.yml
          3/modules/classban.md: 4/modules/classban.yml
          3/modules/clearchan.md: 4/modules/clearchan.yml
          3/modules/cloaking.md: 4/modules/cloak.yml
          3/modules/clones.md: 4/moved-modules.md
          3/modules/codepage.md: 4/modules/codepage.yml
          3/modules/commonchans.md: 4/modules/commonchans.yml
          3/modules/conn_join.md: 4/modules/conn_join.yml
          3/modules/conn_umodes.md: 4/modules/conn_umodes.yml
          3/modules/conn_waitpong.md: 4/modules/conn_waitpong.yml
          3/modules/connectban.md: 4/modules/connectban.yml
          3/modules/connflood.md: 4/modules/connflood.yml
          3/modules/customprefix.md: 4/modules/customprefix.yml
          3/modules/customtitle.md: 4/modules/customtitle.yml
          3/modules/cycle.md: 4/modules/cycle.yml
          3/modules/dccallow.md: 4/modules/dccallow.yml
          3/modules/deaf.md: 4/modules/deaf.yml
          3/modules/delayjoin.md: 4/modules/delayjoin.yml
          3/modules/delaymsg.md: 4/modules/delaymsg.yml
          3/modules/denychans.md: 4/modules/denychans.yml
          3/modules/disable.md: 4/modules/disable.yml
          3/modules/dnsbl.md: 4/modules/dnsbl.yml
          3/modules/exemptchanops.md: 4/modules/exemptchanops.yml
          3/modules/filter.md: 4/modules/filter.yml
          3/modules/gecosban.md: 4/modules/realnameban.yml
          3/modules/geo_maxmind.md: 4/modules/geo_maxmind.yml
          3/modules/geoban.md: 4/modules/geoban.yml
          3/modules/geoclass.md: 4/modules/geoclass.yml
          3/modules/globalload.md: 4/modules/globalload.yml
          3/modules/globops.md: 4/modules/globops.yml
          3/modules/haproxy.md: 4/modules/haproxy.yml
          3/modules/helpop.md: 4/modules/help.yml
          3/modules/hidechans.md: 4/modules/hidechans.yml
          3/modules/hidelist.md: 4/modules/hidelist.yml
          3/modules/hidemode.md: 4/modules/hidemode.yml
          3/modules/hideoper.md: 4/modules/hideoper.yml
          3/modules/hostchange.md: 4/moved-modules.md
          3/modules/hostcycle.md: 4/modules/hostcycle.yml
          3/modules/httpd.md: 4/modules/httpd.yml
          3/modules/httpd_acl.md: 4/modules/httpd_acl.yml
          3/modules/httpd_config.md: 4/modules/httpd_config.yml
          3/modules/httpd_stats.md: 4/modules/httpd_stats.yml
          3/modules/ident.md: 4/modules/ident.yml
          3/modules/index.md: 4/modules/index.md
          3/modules/inviteexception.md: 4/modules/inviteexception.yml
          3/modules/ircv3.md: 4/modules/ircv3.yml
          3/modules/ircv3_accounttag.md: 4/modules/ircv3_accounttag.yml
          3/modules/ircv3_batch.md: 4/modules/ircv3_batch.yml
          3/modules/ircv3_capnotify.md: 4/modules/ircv3_capnotify.yml
          3/modules/ircv3_chghost.md: 4/modules/ircv3_chghost.yml
          3/modules/ircv3_ctctags.md: 4/modules/ircv3_ctctags.yml
          3/modules/ircv3_echomessage.md: 4/modules/ircv3_echomessage.yml
          3/modules/ircv3_invitenotify.md: 4/modules/ircv3_invitenotify.yml
          3/modules/ircv3_labeledresponse.md: 4/modules/ircv3_labeledresponse.yml
          3/modules/ircv3_msgid.md: 4/modules/ircv3_msgid.yml
          3/modules/ircv3_servertime.md: 4/modules/ircv3_servertime.yml
          3/modules/ircv3_sts.md: 4/modules/ircv3_sts.yml
          3/modules/joinflood.md: 4/modules/joinflood.yml
          3/modules/kicknorejoin.md: 4/modules/kicknorejoin.yml
          3/modules/knock.md: 4/modules/knock.yml
          3/modules/ldap.md: 4/modules/ldap.yml
          3/modules/ldapauth.md: 4/modules/ldapauth.yml
          3/modules/ldapoper.md: 4/modules/ldapoper.yml
          3/modules/lockserv.md: 4/moved-modules.md
          3/modules/maphide.md: 4/modules/maphide.yml
          3/modules/md5.md: 4/modules/md5.yml
          3/modules/messageflood.md: 4/modules/messageflood.yml
          3/modules/mlock.md: 4/modules/services.yml
          3/modules/modenotice.md: 4/moved-modules.md
          3/modules/monitor.md: 4/modules/monitor.yml
          3/modules/muteban.md: 4/modules/muteban.yml
          3/modules/mysql.md: 4/modules/mysql.yml
          3/modules/namedmodes.md: 4/modules/namedmodes.yml
          3/modules/namesx.md: 4/modules/multiprefix.yml
          3/modules/nationalchars.md: 4/modules/codepage.yml
          3/modules/nickflood.md: 4/modules/nickflood.yml
          3/modules/nicklock.md: 4/modules/nicklock.yml
          3/modules/noctcp.md: 4/modules/noctcp.yml
          3/modules/nokicks.md: 4/modules/nokicks.yml
          3/modules/nonicks.md: 4/modules/nonicks.yml
          3/modules/nonotice.md: 4/modules/nonotice.yml
          3/modules/nopartmsg.md: 4/moved-modules.md
          3/modules/ojoin.md: 4/modules/ojoin.yml
          3/modules/operchans.md: 4/modules/operchans.yml
          3/modules/operjoin.md: 4/modules/operjoin.yml
          3/modules/operlevels.md: 4/modules/operlevels.yml
          3/modules/operlog.md: 4/modules/operlog.yml
          3/modules/opermodes.md: 4/modules/opermodes.yml
          3/modules/opermotd.md: 4/modules/opermotd.yml
          3/modules/operprefix.md: 4/modules/operprefix.yml
          3/modules/override.md: 4/modules/override.yml
          3/modules/passforward.md: 4/modules/passforward.yml
          3/modules/password_hash.md: 4/modules/password_hash.yml
          3/modules/pbkdf2.md: 4/modules/pbkdf2.yml
          3/modules/permchannels.md: 4/modules/permchannels.yml
          3/modules/pgsql.md: 4/modules/pgsql.yml
          3/modules/randquote.md: 4/modules/randquote.yml
          3/modules/redirect.md: 4/modules/redirect.yml
          3/modules/regex_glob.md: 4/modules/regex_glob.yml
          3/modules/regex_pcre.md: 4/modules/regex_pcre2.yml
          3/modules/regex_pcre2.md: 4/modules/regex_pcre2.yml
          3/modules/regex_posix.md: 4/modules/regex_posix.yml
          3/modules/regex_re2.md: 4/modules/regex_re2.yml
          3/modules/regex_stdlib.md: 4/modules/regex_stdlib.yml
          3/modules/regex_tre.md: 4/modules/regex_tre.yml
          3/modules/remove.md: 4/modules/remove.yml
          3/modules/repeat.md: 4/modules/repeat.yml
          3/modules/restrictchans.md: 4/modules/restrictchans.yml
          3/modules/restrictmsg.md: 4/modules/restrictmsg.yml
          3/modules/rline.md: 4/modules/rline.yml
          3/modules/rmode.md: 4/modules/rmode.yml
          3/modules/sajoin.md: 4/modules/sajoin.yml
          3/modules/sakick.md: 4/modules/sakick.yml
          3/modules/samode.md: 4/modules/samode.yml
          3/modules/sanick.md: 4/modules/sanick.yml
          3/modules/sapart.md: 4/modules/sapart.yml
          3/modules/saquit.md: 4/modules/saquit.yml
          3/modules/sasl.md: 4/modules/sasl.yml
          3/modules/satopic.md: 4/modules/satopic.yml
          3/modules/securelist.md: 4/modules/securelist.yml
          3/modules/seenicks.md: 4/modules/seenicks.yml
          3/modules/serverban.md: 4/modules/serverban.yml
          3/modules/services_account.md: 4/modules/account.yml
          3/modules/servprotect.md: 4/modules/services.yml
          3/modules/sethost.md: 4/modules/sethost.yml
          3/modules/setident.md: 4/modules/setident.yml
          3/modules/setidle.md: 4/modules/setidle.yml
          3/modules/setname.md: 4/modules/setname.yml
          3/modules/sha1.md: 4/modules/sha1.yml
          3/modules/sha256.md: 4/modules/sha2.yml
          3/modules/showfile.md: 4/modules/showfile.yml
          3/modules/showwhois.md: 4/modules/showwhois.yml
          3/modules/shun.md: 4/modules/shun.yml
          3/modules/silence.md: 4/modules/silence.yml
          3/modules/spanningtree.md: 4/modules/spanningtree.yml
          3/modules/sqlauth.md: 4/modules/sqlauth.yml
          3/modules/sqlite3.md: 4/modules/sqlite3.yml
          3/modules/sqloper.md: 4/modules/sqloper.yml
          3/modules/ssl_gnutls.md: 4/modules/ssl_gnutls.yml
          3/modules/ssl_mbedtls.md: 4/moved-modules.md
          3/modules/ssl_openssl.md: 4/modules/ssl_openssl.yml
          3/modules/sslinfo.md: 4/modules/sslinfo.yml
          3/modules/sslmodes.md: 4/modules/sslmodes.yml
          3/modules/sslrehashsignal.md: 4/modules/sslrehashsignal.yml
          3/modules/starttls.md: 4/modules/starttls.yml
          3/modules/stripcolor.md: 4/modules/stripcolor.yml
          3/modules/svshold.md: 4/modules/services.yml
          3/modules/swhois.md: 4/modules/swhois.yml
          3/modules/timedbans.md: 4/modules/timedbans.yml
          3/modules/tline.md: 4/modules/tline.yml
          3/modules/topiclock.md: 4/modules/services.yml
          3/modules/uhnames.md: 4/modules/uhnames.yml
          3/modules/uninvite.md: 4/modules/uninvite.yml
          3/modules/userip.md: 4/moved-modules.md
          3/modules/vhost.md: 4/modules/vhost.yml
          3/modules/watch.md: 4/modules/watch.yml
          3/modules/websocket.md: 4/modules/websocket.yml
          3/modules/xline_db.md: 4/modules/xline_db.yml
          3/snomasks.md: 4/snomasks.md
          3/user-modes.md: 4/user-modes.md
          4/index.md: index.md
          social.md: support.md
