name: security
description: |-
  The `<security>` tag defines configuration options relating to server security. This tag can only be defined once.
attributes:
- name: announceinvites
  type: Text
  required: false
  default: dynamic
  description: |-
    Whether to send an announcement when a user is invited to a channel.
- name: customversion
  type: Text
  required: false
  default: null
  description: |-
    A custom string to show in the `/VERSION` output.
- name: genericoper
  type: Boolean
  required: false
  default: 'No'
  description: |-
    Whether to show "is a server operator" in `/WHOIS` instead of the server operator's type.
- name: publicxlinequit
  type: Text
  required: false
  default: null
  description: |-
    If non-empty then the quit message to show to non-server operators instead of the X-Line reason.
- name: hidekills
  type: Text
  required: false
  default: null
  description: |-
    If defined then the text to show in a kill message instead of the name of the server operator who caused the kill.
- name: hideserver
  type: Text
  required: false
  default: null
  description: |-
    If defined then the text to show in place of a server name.
- name: hideservicekills
  type: Boolean
  required: false
  default: 'No'
  description: |-
    Whether to hide server notices about kills by users on services servers.
- name: maxtargets
  type: Number
  required: false
  default: '20'
  description: |-
    The maximum number of targets a user may specify in a command.
- name: restrictbannedusers
  type: Text
  required: false
  default: 'Yes'
  description: |-
    Whether to restrict the behaviour of users who are banned in a channel.
- name: runasgroup
  type: Text
  required: false
  default: null
  description: |-
    If defined then the group to switch to after starting up (requires starting as root).
- name: runasuser
  type: Text
  required: false
  default: null
  description: |-
    If defined then the user to switch to after starting up (requires starting as root).
- name: userstats
  type: Text
  required: false
  default: Pu
  description: |-
    The `/STATS` characters that a non-server operator can view.
details: |+
  The announceinvites field should be set to one of the following values:

  Value   | Description
  ------- | -----------
  none    | Don't send any invite announcements.
  ops     | Send invite announcements to channel operators and higher ranked users.
  dynamic | Send invites to channel half-operators (if available) and higher ranked users.
  all     | Send invites to all channel members.

  The publicxlinequit field can contain any of the following template variables:

  Variable    | Description
  ----------- | -----------
  %created%   |  The date/time at which the X-line was created.
  %duration%  |  The duration of the X-line.
  %expiry%    |  The date/time at which the X-line expires.
  %fulltype%  |  The type of X-line which was matched, suffixed with  "-lined" if its name is one or two characters.
  %reason%    |  The reason the X-line was added.
  %remaining% |  The duration remaining on the X-line.
  %setter%    |  The name of the X-line setter.
  %type%      |  The type of X-line that was matched.

  The restrictbannedusers field should be set to one of the following values:

  Value  | Description
  ------ | -----------
  yes    | Banned users should be restricted.
  no     | Banned users should not be restricted.
  silent | Banned users should be restricted but should not be informed.

example: |-
  ```xml
  <security announceinvites="dynamic"
            customversion=""
            genericoper="no"
            publicxlinequit=""
            hidekills=""
            hideserver=""
            hideservicekills="yes"
            maxtargets="20"
            restrictbannedusers="yes"
            runasgroup=""
            runasuser=""
            userstats="Pu">
  ```
