#!/usr/bin/env ruby
ROOT = File.dirname __dir__

missing = Array.new
Dir["#{ROOT}/docs/**/*.md"].each do |file|
	contents = File.read(file)
	contents.scan(/\[[^\]]+\]\(\/([^\)]+?)\/?(?:\#[^\)]+|\/)?\)/).each do |link|
		next if link[0].include? "{{"  # Jinja variable
		next if File.exist? "#{ROOT}/docs/#{link[0]}.md"
		next if File.exist? "#{ROOT}/docs/#{link[0]}.yml"
		next if File.exist? "#{ROOT}/docs/#{link[0]}/index.md"
		missing << link[0] unless missing.include? link[0]
	end
	contents.scan(/\{!\s*(\S+)\s*!\}/).each do |fragment|
		next if File.exist? "#{ROOT}/docs/#{fragment[0]}"
		missing << fragment[0] unless missing.include? fragment[0]
	end
end

missing.sort.each do |link|
	absolute_link = "#{ROOT}/docs/#{link}"
	absolute_link += '/index.md' if File.exist? absolute_link
	puts "Missing: #{absolute_link}"
end
puts "#{missing.size} missing!"
exit missing.size
